// penn.jp/

import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Feed } from 'src/components/templates/Feed';
import { ArticleFilter } from 'src/components/templates/ArticleFilter'
import { Header } from 'src/components/templates/Header';
import { SideWidget } from 'src/components/templates/SideWidget';

const Home: NextPage = () => {

  

  return (
    <>  
      <Head>
        <title>penn</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <div className='container font-Poppins text-penn-dark'>
        <main className='flex justify-around'>
          <div className='flex flex-col'>
            <ArticleFilter />
            <Feed />
          </div>
          <div className='mx-6'>
            <SideWidget />
          </div>
        </main>
      </div>
    </>
  );
};

export default Home;
