// penn.jp/
import type { NextPage } from 'next';
import Head from 'next/head';

import PublicFeed from 'src/components/templates/PublicFeed';
import { Header } from 'src/components/templates/Header';
import { SideWidget } from 'src/components/templates/SideWidget';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>penn</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='dark:bg-black transition duration-500'>
          <Header />
          <div className='container font-Poppins text-penn-dark dark:text-penn-light'>
            {/* justify-between で要素の幅が固定されている */}
            <main className='flex justify-between gap-10'>
              <PublicFeed />
              <SideWidget />
            </main>
          </div>
        </div>
    </>
  );
};

export default Home;
